### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by billytheman42069** [memetrollsXD/crepe.moe#11]
I have no idea what I am doing and I don't know how to install this. I have nginx running and as far as I know I should be going to the crepe.moe folder and running npm install, but I have no idea what to do from there, or where I should be configuring changes. I tried looking up how to install and run typescript packages but that is as far as I got. Are there any plans to add installation instructions for people like me? Thanks.

**Comment by memetrollsXD** [comment]
1. `npm install`
2. `npm start`

That's it. Then it should be accessible under localhost:8008 or whatever port you set it to on config.

Additionally, you can then configure nginx as a reverse proxy or setup [forever](https://github.com/foreversd/forever).
