### ISSUE TITLE
About the server

### ISSUE THREAD

**Issue by zipdata** [memetrollsXD/crepe.moe#3]
When I wanted to visit this website, I found that it seemed to be attacked by ddos. Can you restart the server?pls

**Comment by memetrollsXD** [comment]
Hi,

crepe.moe is not being ddosed, but had a spike of requests (3-5 requests per second). It’s really hard to send a file to 20 thousand people at once, especially when you only have 1 VPS and 1 gbps port. You should be able to visit the site normally now though.
